const TEXT = (value: unknown) => (typeof value === 'string' ? value.trim() : value == null ? '' : `${value}`.trim());

const NORM = (value: unknown) =>
  TEXT(value)
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[ÃÂ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();

// Source: "Datos campañas Visualizador de Financiamiento Político - NOMBRES.tsv"
const CANDIDATE_PARTY_ENTRIES = [
  ['Alain Albenis Cedeño Herrera', 'Realizando Metas'],
  ['Albercio Ellis Bonilla', 'Partido Revolucionario Democrático'],
  ['Alberto Melamed Gonzalez', 'Partido Revolucionario Democrático'],
  ['Alex Ariel Wright Castillo', 'Realizando Metas'],
  ['Alexander Alexis Chavarria Arauz', 'Partido Panameñista'],
  ['Alexandra Maria Brenes Samaniego', 'Libre Postulación'],
  ['Amado Cherif Franco Bustamante', 'Cambio Democrático'],
  ['Amed Zamar Meza Madiedo', 'Partido Panameñista'],
  ['Angel Batista Barria', 'Partido Panameñista'],
  ['Anibal Hartemio Dominguez Frias', 'Partido Revolucionario Democrático'],
  ['Antonio Pope Bernal', 'Alianza'],
  ['Arcenio Ortiz Perez', 'Alianza'],
  ['Arcesio Alberto Ticas Gallardo', 'Partido Revolucionario Democrático'],
  ['Ariana Marisin Coba Martinez', 'Partido Panameñista'],
  ['Ariel Ulises Vallarino Aparicio', 'Realizando Metas'],
  ['Arquesio Arias Felix', 'Partido Revolucionario Democrático'],
  ['Augusto Efrain Palacios Muñoz', 'Libre Postulación'],
  ['Benicio Enacio Robinson Grajales', 'Partido Revolucionario Democrático'],
  ['Benito Filemon Serrano Chito', 'Partido Revolucionario Democrático'],
  ['Bernabela Virola Garcia', 'Partido Revolucionario Democrático'],
  ['Betserai Ayize Richards Tapia', 'Libre Postulación'],
  ['Carlos Agustin Afu Decerega', 'Cambio Democrático'],
  ['Carlos Alberto Chavarria Cerezo', 'Molirena'],
  ['Carlos Eduardo Saldaña Lopez', 'Libre Postulación'],
  ['Chuin Fa Chong Wong', 'Cambio Democrático'],
  ['Crispiano Adames Navarro', 'Partido Revolucionario Democrático'],
  ['Dana Daris Castañeda Guardia', 'Realizando Metas'],
  ['Daniel Berrugate Puchicama', 'Partido Revolucionario Democrático'],
  ['Didiano Pinilla Rios', 'Cambio Democrático'],
  ['Doris Anays Atencio Coba', 'Partido Revolucionario Democrático'],
  ['Edilberto Medina Mejia', 'Partido Revolucionario Democrático'],
  ['Eduardo Alejandro Gaitan Beitia', 'Libre Postulación'],
  ['Eduardo Enrique Vasquez Gutierrez', 'Cambio Democrático'],
  ['Eduardo Rodriguez', 'Cambio Democrático'],
  ['Edwin Antonio Vergara Castillo', 'Partido Panameñista'],
  ['Edwin Javier Martinez Barba', 'Realizando Metas'],
  ['Eliecer Bredio Cortes Castro', 'Partido Revolucionario Democrático'],
  ['Eliecer Castrellon Barrios', 'Partido Popular'],
  ['Emilio Smith Pineda', 'Cambio Democrático'],
  ['Eric Eligio Dominguez Villarreal', 'Partido Revolucionario Democrático'],
  ['Eric Javier Jaen Vega', 'Movimiento Otro Camino'],
  ['Ernesto Cedeño Alvarado', 'Movimiento Otro Camino'],
  ['Eugenio Delgado Perez', 'Partido Revolucionario Democrático'],
  ['Eulalio Yanguez Ruiz', 'Cambio Democrático'],
  ['Ezequiel Rodriguez González', 'Molirena'],
  ['Fermin Jimenez Ortega', 'Partido Revolucionario Democrático'],
  ['Fermin Saldaña Garcia', 'Partido Revolucionario Democrático'],
  ['Flor Isabel Brenes Medina', 'Partido Revolucionario Democrático'],
  ['Francisco Aurelio Leon Fu Herrera', 'Realizando Metas'],
  ['Francisco Javier Agapi Chami', 'Partido Revolucionario Democrático'],
  ['Francisco Javier Brea Clavel', 'Partido Panameñista'],
  ['Francisco Javier Brea Tristan', 'Partido Panameñista'],
  ['Franklin Enrique Valdes Pitty', 'Partido Panameñista'],
  ['Gertrudis Rodriguez Degracia', 'Cambio Democrático'],
  ['Graciela Mercedes Hernandez Lacayo', 'Movimiento Otro Camino'],
  ['Gustavo Adriano Polanco Mastrolinardo', 'Partido Revolucionario Democrático'],
  ['Harry De Jesus Agrazal Monterrey', 'Alianza'],
  ['Hipólito Jimenez Santos', 'Partido Panameñista'],
  ['Hortencio Dario Palma Blanco', 'Partido Panameñista'],
  ['Humberto Sanchez Ortiz', 'Partido Revolucionario Democrático'],
  ['Ina Daneth Rodriguez Castañeda', 'Realizando Metas'],
  ['Irma Eneida Hernandez Berrio', 'Libre Postulación'],
  ['Isaac Mosquera Rivas', 'Molirena'],
  ['Ivan Eladio De Leon Banda', 'Partido Panameñista'],
  ['Jaime Edgardo Vargas Centella', 'Partido Revolucionario Democrático'],
  ['Jairo Ariel Salazar Ramirez', 'Partido Revolucionario Democrático'],
  ['Jamis Gaspar Acosta Guerra', 'Realizando Metas'],
  ['Janine Prado Castaño', 'Libre Postulación'],
  ['Jannelle Dadineth Gonzalez Logreira', 'Partido Revolucionario Democrático'],
  ['Javier Francisco Sucre Mejia', 'Partido Revolucionario Democrático'],
  ['Jesenka Marlowa Espinosa Rios', 'Partido Revolucionario Democrático'],
  ['Jhonathan Edir Vega', 'Libre Postulación'],
  ['Joan Manuel Guevara Rodriguez', 'Alianza'],
  ['Joaquin De Leon Rivera', 'Partido Panameñista'],
  ['Jorge Alberto Gonzalez Lopez', 'Libre Postulación'],
  ['Jorge Isaac Bloise Iglesias', 'Libre Postulación'],
  ['Jorge Luis Herrera', 'Partido Panameñista'],
  ['Jose Antonio Perez Barboni', 'Movimiento Otro Camino'],
  ['José Gabriel Carrizo Jaen', 'Partido Revolucionario Democrático'],
  ['Jose Irene Lasprilla Linares', 'Cambio Democrático'],
  ['Jose Ismael Tristan Aguilar', 'Partido Revolucionario Democrático'],
  ['Jose Luis Varela Rodriguez', 'Partido Panameñista'],
  ['José Raúl Mulino Quintero', 'Realizando Metas'],
  ['Juan Carlos Huerta Solis', 'Partido Revolucionario Democrático'],
  ['Juan Gabriel Jaramillo Ramos', 'Realizando Metas'],
  ['Juaquin Aguirre Montezuma', 'Molirena'],
  ['Julio De La Guardia Arrocha', 'Cambio Democrático'],
  ['Ket Wong Yau Martinez', 'Realizando Metas'],
  ['Lenin Alberto Ulate Rodriguez', 'Libre Postulación'],
  ['Lilia Emerita Batista Rodriguez', 'Realizando Metas'],
  ['Lorenzo Diogenes Galvan Niño', 'Libre Postulación'],
  ['Luis Eduardo Camacho Castro', 'Realizando Metas'],
  ['Luis Henrique Duke Walker', 'Libre Postulación'],
  ['Luis Manuel Estribi Miranda', 'Partido Popular'],
  ['Luis Omar Ortega Rivera', 'Realizando Metas'],
  ['Manuel Alberto Samaniego Rodriguez', 'Libre Postulación'],
  ['Manuel Cohen Salerno', 'Cambio Democrático'],
  ['Manuel Ernesto Soriano Cedeño', 'Partido Panameñista'],
  ['Marcos Enrique Castillero Barahona', 'Partido Revolucionario Democrático'],
  ['Maribel Gordon Calderon', 'Libre Postulación'],
  ['Martin Erasto Torrijos Espino', 'Partido Popular'],
  ['Medin Jimenez Pitti', 'Partido Panameñista'],
  ['Meliton Alejandro Arrocha Ruiz', 'País'],
  ['Miguel Angel Campos Lima', 'Libre Postulación'],
  ['Miguel Fernando Batista Dominguez', 'Cambio Democrático'],
  ['Miguel Ricaurte Pitti Caballero', 'Partido Popular'],
  ['Neftali Omar Zamora Ibarra', 'Libre Postulación'],
  ['Nelson Jackson Palma', 'Partido Revolucionario Democrático'],
  ['Nestor Antonio Guardia Jaen', 'Partido Revolucionario Democrático'],
  ['Nicolas Ameth Zapata Serrano', 'Partido Revolucionario Democrático'],
  ['Nixson Andrade Rodriguez', 'Partido Revolucionario Democrático'],
  ['Noe Ivan Herrera Rivera', 'Partido Revolucionario Democrático'],
  ['Olga Paulette Thomas Horly', 'Libre Postulación'],
  ['Omar Enrique Bultron Valdes', 'Partido Panameñista'],
  ['Orlando Vladimir Carrasquilla Bonilla', 'Cambio Democrático'],
  ['Osman Camilo Gomez', 'Alianza'],
  ['Osman Dionel Bernal Cedeño', 'Partido Panameñista'],
  ['Osvaldo Abel Gonzalez Samaniego', 'Realizando Metas'],
  ['Patsy Cristina Lee Renteria', 'Partido Popular'],
  ['Pedro Camaño Otero', 'Libre Postulación'],
  ['Quintin Pitti Chanto', 'Partido Panameñista'],
  ['Rafael Quintero Gonzalez', 'Cambio Democrático'],
  ['Ramon Roberto Ramos Batista', 'Cambio Democrático'],
  ['Raphael Buchanan Joseph', 'Partido Revolucionario Democrático'],
  ['Raul Alberto Montenegro Vergara', 'Libre Postulación'],
  ['Raul Gilberto Pineda Vergara', 'Partido Revolucionario Democrático'],
  ['Ricardo Agustin Vigil Lopez', 'Partido Panameñista'],
  ['Ricardo Alberto Lombana Gonzalez', 'Movimiento Otro Camino'],
  ['Ricardo Alberto Martinelli Berrocal', 'Realizando Metas'],
  ['Roberto Archibold Chuito', 'Partido Panameñista'],
  ['Roberto José Federico Zuñiga Alvarado', 'Libre Postulación'],
  ['Robin Kam Gallardo', 'Realizando Metas'],
  ['Rogelio Ricardo Revello Tem', 'Realizando Metas'],
  ['Ronald Ameth De Gracia Moreno', 'Realizando Metas'],
  ['Ruben Dario Lorenzo Rios Rios', 'Realizando Metas'],
  ['Salustiano Mojica Vergara', 'Realizando Metas'],
  ['Samuel Santiago Archibold', 'Partido Revolucionario Democrático'],
  ['Sergio Rafael Galvez Evers', 'Realizando Metas'],
  ['Shirley De La Rosa Castañedas Valentin', 'Realizando Metas'],
  ['Stefany Dayan Peñalba', 'Libre Postulación'],
  ['Tomas Gabriel Benavides Aguilar', 'Realizando Metas'],
  ['Tomas Robles Acosta', 'Partido Revolucionario Democrático'],
  ['Victor De Gracia Rodriguez', 'Partido Revolucionario Democrático'],
  ['Victor De Jesus Castillo Cortez', 'Realizando Metas'],
  ['Vielka Galvez Ballesteros', 'Partido Revolucionario Democrático'],
  ["Walkiria Aurora Chandler D'Orcy", 'Libre Postulación'],
  ['Wilbur Martinez Dixon', 'Partido Revolucionario Democrático'],
  ['Yamileth Itzela Cruz Rios', 'Libre Postulación'],
  ['Yamireliz Daymirelkis Chong Smith', 'Libre Postulación'],
  ['Yarelis Anayansi Rodriguez Batista', 'Libre Postulación'],
  ['Yecenia Marina Alfonso Martinez', 'Partido Popular'],
  ['Yenia Yamara Julio', 'Cambio Democrático'],
  ['Yesica Romero Garcia', 'Cambio Democrático'],
  ['Yuzaida Andrea Marin Nateron', 'Realizando Metas'],
  ['Zulay Leyset Rodriguez Lu', 'Libre Postulación'],
  ['Manuel Cheng Peñalba', 'Libre Postulación'],
  ['Mayer Mizrachi Matalon', 'Partido Popular'],
  ['Romulo Alberto Roux Moses', 'Cambio Democrático'],
] as const;

const SOURCE_NAME_ALIASES = new Map([
  [NORM('Nicolas Zapata Serrano'), NORM('Nicolas Ameth Zapata Serrano')],
  [NORM('Rubendario Lorenzo Rios Rios'), NORM('Ruben Dario Lorenzo Rios Rios')],
]);

const CANDIDATE_PARTIES_BY_NORM = new Map(CANDIDATE_PARTY_ENTRIES.map(([name, party]) => [NORM(name), party]));

export function getCandidatePartyOverride(candidateName: string | null | undefined): string | null {
  const key = NORM(candidateName);
  if (!key) return null;
  return CANDIDATE_PARTIES_BY_NORM.get(SOURCE_NAME_ALIASES.get(key) ?? key) ?? null;
}
