/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents_.$documentId'
import { Route as DocumentsDiscrepanciasRouteImport } from './routes/documents/discrepancias'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'

const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents_/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDiscrepanciasRoute = DocumentsDiscrepanciasRouteImport.update({
  id: '/discrepancias',
  path: '/discrepancias',
  getParentRoute: () => DocumentsRoute,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/documents/discrepancias': typeof DocumentsDiscrepanciasRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents/': typeof DocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/documents/discrepancias': typeof DocumentsDiscrepanciasRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents': typeof DocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/documents/discrepancias': typeof DocumentsDiscrepanciasRoute
  '/documents_/$documentId': typeof DocumentsDocumentIdRoute
  '/documents/': typeof DocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/documents'
    | '/authenticated'
    | '/documents/discrepancias'
    | '/documents/$documentId'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/authenticated'
    | '/documents/discrepancias'
    | '/documents/$documentId'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/documents'
    | '/_authenticated/authenticated'
    | '/documents/discrepancias'
    | '/documents_/$documentId'
    | '/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents_/$documentId': {
      id: '/documents_/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/discrepancias': {
      id: '/documents/discrepancias'
      path: '/discrepancias'
      fullPath: '/documents/discrepancias'
      preLoaderRoute: typeof DocumentsDiscrepanciasRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DocumentsRouteChildren {
  DocumentsDiscrepanciasRoute: typeof DocumentsDiscrepanciasRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDiscrepanciasRoute: DocumentsDiscrepanciasRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
